### ISSUE TITLE
vi keybindings support

### ISSUE THREAD

**Issue by pythops** [rhysd/tui-textarea#19]
would be great to support the vi key bindings :pray:

**Comment by AmmarAbouZor** [comment]
I believe there is an example how to achieve that within the examples in this repo. You still need to add the keybindigs and manage the modes manually though.

**Comment by rhysd** [comment]
[`modal` example](https://github.com/rhysd/tui-textarea/blob/main/examples/modal.rs) is available. Since vi provides tons of key bindings, it is not possible to emulate all of them. If some of them are mandatory for you and not possible with current tui-textarea's APIs, please make a feature request respectively.
