### ISSUE TITLE
Why shift is hardcoded here ?

### ISSUE THREAD

**Issue by 0b-s3rv3r** [rhysd/tui-textarea#68]
https://github.com/rhysd/tui-textarea/blob/39075bb641f340d85175328249ba97aac0b16e04/src/input/termion.rs#L51

Why shift is hardcoded here as always false ? This is why I can't make combinations like Shift+Enter for example.

**Comment by 0watcher** [comment]
It's very misleading, when I write something like this for example and It always receives false.
```rust
Input {
                    key: Key::Enter,
                    ctrl: false,
                    shift: is_shift,
                    ..
} => {
   if is_shift {
   textarea.insert_new_line();
   }
}          
```

**Comment by ProHaller** [comment]
I've got the same issue! I've been agonizing over it. Any way to activate it?

**Comment by 0watcher** [comment]
I guess we can use crosster::event::KeyCode, instead of using Input from tui-textarea, because KeyCode implements Into<Input>, but i didn't check if it works.

```rust
        let timeout = Duration::from_millis(10);
        if event::poll(timeout)? {
            if let Event::Key(key_event) = event::read()? {
                match key_event.code {
                    KeyCode::Enter if key_event.modifiers.contains(KeyModifiers::Shift) => {}
                    _ => self.textarea.input(key_event.into())
                }
            }
         }
```

**Comment by 0watcher** [comment]
I've checked this and with crossterm::KeyCode it also doesn't work. Idk why.

**Comment by rhysd** [comment]
> Why shift is hardcoded here ?

That's because (if my understanding is correct) there is no way to get if shift key was pressed or not. termion supports `Key::Ctrl(char)` and `Key::Alt(char)` so we can know Ctrl and Alt modifier keys were held. We need to detect shift modifier press from other event like `Key::ShiftLeft` and `Key::ShiftLeftUp`. However the method `fn from(key: KeyEvent) -> Self` needs to convert a single `Key` event into `Input` instance so there is no way to detect shift key press.

You need to set the `shift` field separately by looking at key events related to shift keydown/keyup in your event loop.

https://docs.rs/termion/latest/termion/event/enum.Key.html#variant.Ctrl

**Comment by rhysd** [comment]
> Why shift is hardcoded here ?

Because termion does not provide a way to handle shift modifier state.

`termion::Event::Key` provides `Ctrl(char)` and `Alt(char)` events so we can handle the state of ctrl and alt modifier keys. However, same functionality is not provided for shift key.

https://docs.rs/termion/latest/termion/event/enum.Key.html

There are some key combinatons with shift key like `ShiftUp`, `ShiftLeft`, ... but there is no `Shift(char)` generic event.

Instead, termion sends the input key as-is. For example, when `Shift + a` is pressed with US keyboard, termion sends `Char('A')`. We cannot know how the 'A' was sent. Generally it was sent by `Shift + a`, but it is completely up to user's keyboard layout.

So I thought `shift` field could not be set in the `from` function. Users may somehow set the `shift` field properly later.

If there is a nice way to properly set the `shift` key in the `from` function without assuming user's keyboard layout, PR is welcome.

**Comment by rhysd** [comment]
I added some more combinations with arrow keys at c4f1b22.

termion added support for those combinations at v4. As long as shift + arrow keys combinations, `shift` field is set properly.

https://github.com/redox-os/termion/commit/3b52dc9bfb22da591a7b86a76a2e7234c45db08f
